apiVersion: batch/v1
kind: Job
metadata:
  name: iperf
spec:
  template:
    metadata:
      name: iperf-client
    spec:
      containers:
      - name: iperf-client-container
        image: networkstatic/iperf3
        args: ["-c" , "10.98.170.122", "-n", "20G"]
      restartPolicy: Never
      nodeSelector: 
        color2: red
