apiVersion: batch/v1
kind: Job
metadata:
  name: iperf
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: iperf-client
    spec:
      containers:
      - name: iperf-client-container
        image: networkstatic/iperf3
        env:
        - name: TOTAL_SIZE
          value: "200G"
        #- name: SERVER_IP
        #  value: ""  
        args: ["-c $(SERVER_IP) -n $(TOTAL_SIZE)"]
      nodeSelector:
        color: blue
      restartPolicy: Never
