apiVersion: apps/v1beta1 # docker run  -it --rm --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s
kind: Deployment
metadata:
  name: iperf-deployment5
  labels:
    app: iperf5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf5
  template:
    metadata:
      labels:
        app: iperf5
    spec:
      containers:
      - name: iperf-server5
        image: networkstatic/iperf3:latest
        ports: 
        - containerPort: 5201
        args: ["-s"]
