apiVersion: batch/v1
kind: Job
metadata:
  name: iperf5
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: iperf-client5
    spec:
      containers:
      - name: iperf-client-container5
        image: networkstatic/iperf3
        args: ["-c" , "10.111.211.177", "-n", "80G"]
      restartPolicy: Never
      nodeSelector: 
        color2: red
