apiVersion: batch/v1
kind: Job
metadata:
  name: iperf4
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: iperf-client4
    spec:
      containers:
      - name: iperf-client-container4
        image: networkstatic/iperf3
        args: ["-c" , "10.108.209.117", "-n", "80G"]
      restartPolicy: Never
      nodeSelector: 
        color2: red
