apiVersion: batch/v1
kind: Job
metadata:
  name: iperf
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: iperf-client
    spec:
      containers:
      - name: iperf-client-container
        image: networkstatic/iperf3
        args: ["-c" , "10.106.124.52", "-n", "80G"]
      restartPolicy: Never
      nodeSelector: 
        color2: red
